export const paginationActiveClassses = 'active bg-gray-500 px-4 mx-1 text-white rounded-sm'
export const userBlockClasses = 'relative w-8 h-8 mr-3 rounded-full md:block'
export const userImageClasses = 'object-cover w-full h-full rounded-full'
export const imageShadowClasses = 'absolute inset-0 rounded-full shadow-inner'
export const usersTableClsses = 'w-full text-sm text-gray-500 dark:text-gray-400 text-center'
export const userTableHeadClasses = 'text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400'
export const usersTableRowClasses = 'bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'
